config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'welcome/index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
		@post = Post.all.limit(3).order("created_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Whoop! you did Justin, you rock!"
		else
			render 'new', notice: "Oh snap, that went wrong, sozzles"
		end
	end

	def show
	end

	def edit
	end
	
	def update
		if @post.update post_params
			redirect_to @post, notice: "Whoop! all good in the hood"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@post = Post.all.limit(3).order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLWithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLWithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Justin Erswell {<%= yield(:title) %>}</title>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<%= link_to "Justin Erswell", root_path, class: "name" %>
		<nav>
			<%= link_to "Articles", posts_path %>
			<a href="#">Projects</a>
			<a href="#">Contact</a>
		</nav>
	</header>

	<%= yield %>

	<footer id="main_footer">
		<p class="copyright">&copy; 2015 Justin Erswell</p>
		<nav>
			<a href="https://bitbucket.org/erswelljustin/" target="_blank"><i class="fa fa-bitbucket"></i></a>
			<a href="https://twitter.com/justin_erswell" target="_blank"><i class="fa fa-twitter"></i></a>
			<a href="https://facebook.com/justin.erswell" target="_blank"><i class="fa fa-facebook-official"></i></a>
		</nav>
	</footer>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
	var disqus_shortname = 'justin-erswell';
	var disqus_identifier = '<%= @post.id %>';
	var disqus_title = '<%= @post.title %>';
	var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
	(function() {
		var d = document, s = d.createElement('script');

		s.src = '//justin-erswell.disqus.com/embed.js';

		s.setAttribute('data-timestamp', +new Date());
		(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluarlize(@post.errors.count, "error") %> prevented this post from saving</h2>
		<ul>
			<% @post.errors.full.messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title%>		
	</div>
	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content%>		
	</div>
	<div class="form-group">
		<%= f.submit %>
	</div>

<% end %>

app/views/posts/edit.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
	<h1 id="page_title">Stuff I've Written</h1>
	<div id="posts_wrapper" class="skinny_wrapper">
		<% @post.each do |post|%>
		<div class="post">
			<p class="date"><%= post.created_at.strftime("%A, %d %B") %></p>
			<h2><a href="#"><%= link_to post.title, post%></a></h2>
			<hr>
		</div>
		<% end %>
	</div>
	<div class="pagination">
		<span class="previous_page disabled">Previous</span>
		<em class="current">1</em>
		<a href="#" rel="next">2</a>
		<a href="#" class="next_page">Next</a>
	</div>	

app/views/posts/new.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<h1>New Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
	<div id="post_show_content" class="skinny_wrapper wrapper_padding">
		<header>
			<p class="date"><%= @post.created_at.strftime("%A, %d %B") %></p>
			<h1><%= @post.title %></h1>
			<hr>
		</header>

		<div id="content">
			<%= markdown @post.content %>
		</div>
		<hr>
		<div id="share_box">
			<p>Share: <b>Adventures in Code</b></p>
			<a onclick="javascript:window.open('https://twitter.com/share?text=<%=@post.title%> by @justin_erswell - &amp;url=<%=url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
			<a onclick="javascript:window.open('https://facebook.com/sharer.php?u=<%=url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook-official"></i></a>
			<a onclick="javascript:window.open('https://plus.google.com/share?url=<%=url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
		</div>
		<hr>
		<p>
			<%= link_to "Edit", edit_post_path(@post) %> |
			<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
		</p>
		<%= render 'disqus' %>	
	</div>

app/views/welcome/index.html.erb
	<div class="wrapper wrapper_padding clearfix">
		<div class="col-1 about homepage_content">
			<h2>About</h2>
			<hr>
			<p>Lorem ipsum dolor sit amet, <a href="#">consectetur</a> adipisicing elit. Quod cum ducimus debitis, harum rerum quia deserunt optio minima.</p>
			<p>Odit asperiores <a href="#">consectetur</a>  assumenda ad nam, ipsum quis dolore atque tempore sunt?</p>
			<p>Ad nam, ipsum quis <a href="#">consectetur</a> atque tempore sunt?</p>
		</div>
		<div class="col-2 homepage_content">
			<h2>Stuff I've Written</h2></a>
			<hr>
			<% @post.each do |post|%>
			<h3><%= link_to post.title, post%></h3>
			<p class="date"><%= post.created_at.strftime("%A, %d %B") %></p>
			<% end %>
		</div>
		<div class="col-3 homepage_content">
			<h2>Stuff I've Built</h2>
			<hr>
			<h3><a href="">Fly Now Pay Later</a></h3>
			<p class="date">Wednesday November 11th</p>
			<h3><a href="">ihub.io</a></h3>
			<p class="date">Wednesday November 11th</p>
			<h3><a href="">Pro Audio Social Stream</a></h3>
			<p class="date">Wednesday November 11th</p>				
		</div>
	</div>